import QueryClientWrapper from "@/components/QueryWrapper";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Code pen",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <QueryClientWrapper>
        <body className={inter.className}>{children}</body>
      </QueryClientWrapper>
    </html>
  );
}
